autograd: python/bun/run_cmpad.py is failing at
  File "/home/bradbell/repo/cmpad.git/python/cmpad/an_ode.py", line 174, in __call__
    yi = self.n * [ Scalar(0.0) ]
                    ^^^^^^^^^^^
TypeError: Box.__init__() missing 2 required positional arguments: 'trace' and 'node'